//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messager.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatUser
    {
        public int ID { get; set; }
        public Nullable<int> ID_ChatRoom { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
    }
}
